### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zwacky**
isrepeatable parameter is bool, otherwise app crashes

### CODE REVIEW

**Comment by pnock** [comment]
Thanks - is this Android or ios?  Your correction is likely OK in all cases, but just want to check that there isn't something else weird going on...

ios *ought* to work with "NO". The native code is using boolValue to assign the native BOOL from the arguments, and "NO" should get parsed as false.

I mistakenly assumed JSONArray.getBoolean() would also convert "YES"/"NO" to true/false. So I think that's where the crash is coming on android.

**Comment by zwacky** [comment]
had it crashing on iOS while isRepeatable was a `"NO"`

**Comment by pnock** [comment]
Hmm, that's a bit weird then.  I'm not seeing that - that native code is using boolValue to convert the javascript argument to BOOL.  For me, "NO", "FALSE", "0", "N", "f" (actually anything that's not explicitly true) just sets the BOOL 'repeatable' to "NO".

Setting false isn't a problem though - it comes through as "0", which boolValue sets to NO. I'll update the readme with some comments, but I'm not sure why this crashes for you.

**Comment by pnock** [comment]
Updated the readme with more detail for this argument.

**Pull request closed without merging**
